name: 'Config Entity Example'
type: module
description: 'Demonstrates how to create a config entity type.'
package: Example modules
core: 8.x
core_version_requirement: ^8 || ^9
dependencies:
  - examples:examples
